### ISSUE TITLE
Build failure due to "Duplicate identifier"

### ISSUE THREAD

**Issue by doron-cohen** [chempogonzalez/vite-plugin-svgr-component#2]
Hi, I am getting the following error when building:
```
❯ yarn build
yarn run v1.22.17
$ tsc && vite build
../node_modules/vite-plugin-svgr-component/client.d.ts:3:18 - error TS2300: Duplicate identifier 'src'.

3   export default component;
                   ~~~~~~~~~

  ../node_modules/vite/client.d.ts:88:18
    88   export default src
                        ~~~
    'src' was also declared here.

../node_modules/vite/client.d.ts:88:18 - error TS2300: Duplicate identifier 'src'.

88   export default src
                    ~~~

  ../node_modules/vite-plugin-svgr-component/client.d.ts:3:18
    3   export default component;
                       ~~~~~~~~~
    'src' was also declared here.


Found 2 errors in 2 files.

Errors  Files
     1  ../node_modules/vite-plugin-svgr-component/client.d.ts:3
     1  ../node_modules/vite/client.d.ts:88
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems that both Vite and the plugin define the module `*.svg`.

I tried to add this line:
```
/// <reference types="vite-plugin-svgr-component/client" />
```
to `vite-env.d.ts` but no luck. I also tried to add another definition for `*.svg?component` and add this suffix to the imports. This solved the issue for Typescript but the imports now fail. What should I do?

**Comment by chempogonzalez** [comment]
Hi! @doron-cohen  sorry for the delayed response. Did you add the following in the first line?
```
/// <reference types="vite-plugin-svgr-component/client" />
```
In the current repo you have a valid working test-app with the proper config. Here you have the links for the files:
- [vite.config.ts ](https://github.com/chempogonzalez/vite-plugin-svgr-component/blob/main/test-app/vite.config.ts)
- [vite-env.d.ts](https://github.com/chempogonzalez/vite-plugin-svgr-component/blob/main/test-app/src/vite-env.d.ts)

**Comment by chempogonzalez** [comment]
This issue will be closed due to the non-activity or possibility of reproducing the error
